// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO Customer (first_name, last_name, email, phone, address, password_hash) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCustomerParams struct {
	FirstName    string
	LastName     string
	Email        string
	Phone        string
	Address      sql.NullString
	PasswordHash string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.PasswordHash,
	)
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT customer_id, first_name, last_name, email, phone, address, loyalty_points, created_at, password_hash FROM Customer WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LoyaltyPoints,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT customer_id, first_name, last_name, email, phone, address, loyalty_points, created_at, password_hash FROM Customer WHERE customer_id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, customerID int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, customerID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LoyaltyPoints,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT customer_id, first_name, last_name, email, phone, address, loyalty_points, created_at, password_hash FROM Customer ORDER BY customer_id
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LoyaltyPoints,
			&i.CreatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomersByName = `-- name: SearchCustomersByName :many
SELECT customer_id, first_name, last_name, email, phone, address, loyalty_points, created_at, password_hash FROM Customer WHERE first_name LIKE ? OR last_name LIKE ? ORDER BY customer_id
`

type SearchCustomersByNameParams struct {
	FirstName string
	LastName  string
}

func (q *Queries) SearchCustomersByName(ctx context.Context, arg SearchCustomersByNameParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomersByName, arg.FirstName, arg.LastName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LoyaltyPoints,
			&i.CreatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerLoyaltyPoints = `-- name: UpdateCustomerLoyaltyPoints :exec
UPDATE Customer SET loyalty_points = ? WHERE customer_id = ?
`

type UpdateCustomerLoyaltyPointsParams struct {
	LoyaltyPoints int32
	CustomerID    int32
}

func (q *Queries) UpdateCustomerLoyaltyPoints(ctx context.Context, arg UpdateCustomerLoyaltyPointsParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerLoyaltyPoints, arg.LoyaltyPoints, arg.CustomerID)
	return err
}
