// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentMethod string

const (
	PaymentMethodCash       PaymentMethod = "cash"
	PaymentMethodCreditCard PaymentMethod = "credit_card"
	PaymentMethodOnline     PaymentMethod = "online"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusCompleted PaymentStatus = "completed"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusRefunded  PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ReservationStatus string

const (
	ReservationStatusPending    ReservationStatus = "pending"
	ReservationStatusConfirmed  ReservationStatus = "confirmed"
	ReservationStatusCheckedIn  ReservationStatus = "checked_in"
	ReservationStatusCheckedOut ReservationStatus = "checked_out"
	ReservationStatusCancelled  ReservationStatus = "cancelled"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type RoomRoomType string

const (
	RoomRoomTypeStandard  RoomRoomType = "Standard"
	RoomRoomTypeDeluxe    RoomRoomType = "Deluxe"
	RoomRoomTypeSuite     RoomRoomType = "Suite"
	RoomRoomTypePenthouse RoomRoomType = "Penthouse"
)

func (e *RoomRoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomRoomType(s)
	case string:
		*e = RoomRoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomRoomType: %T", src)
	}
	return nil
}

type NullRoomRoomType struct {
	RoomRoomType RoomRoomType `json:"room_room_type"`
	Valid        bool         `json:"valid"` // Valid is true if RoomRoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomRoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomRoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomRoomType), nil
}

type StaffRole string

const (
	StaffRoleReceptionist StaffRole = "receptionist"
	StaffRoleManager      StaffRole = "manager"
	StaffRoleAdmin        StaffRole = "admin"
)

func (e *StaffRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffRole(s)
	case string:
		*e = StaffRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffRole: %T", src)
	}
	return nil
}

type NullStaffRole struct {
	StaffRole StaffRole `json:"staff_role"`
	Valid     bool      `json:"valid"` // Valid is true if StaffRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffRole) Scan(value interface{}) error {
	if value == nil {
		ns.StaffRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffRole), nil
}

type Customer struct {
	CustomerID    int32          `json:"customer_id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	Address       sql.NullString `json:"address"`
	LoyaltyPoints int32          `json:"loyalty_points"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	PasswordHash  string         `json:"password_hash"`
}

type Payment struct {
	PaymentID      int32          `json:"payment_id"`
	ReservationID  int32          `json:"reservation_id"`
	Amount         string         `json:"amount"`
	PaymentDate    time.Time      `json:"payment_date"`
	Method         PaymentMethod  `json:"method"`
	TransactionID  sql.NullString `json:"transaction_id"`
	Status         PaymentStatus  `json:"status"`
	BillingName    string         `json:"billing_name"`
	BillingEmail   string         `json:"billing_email"`
	BillingAddress sql.NullString `json:"billing_address"`
}

type Reservation struct {
	ReservationID  int32             `json:"reservation_id"`
	CustomerID     int32             `json:"customer_id"`
	RoomID         int32             `json:"room_id"`
	StaffID        sql.NullInt32     `json:"staff_id"`
	CheckInDate    time.Time         `json:"check_in_date"`
	CheckOutDate   time.Time         `json:"check_out_date"`
	NumberOfGuests int32             `json:"number_of_guests"`
	Status         ReservationStatus `json:"status"`
	BookingDate    time.Time         `json:"booking_date"`
}

type Reservationwithprice struct {
	ReservationID     int32             `json:"reservation_id"`
	CustomerID        int32             `json:"customer_id"`
	RoomID            int32             `json:"room_id"`
	StaffID           sql.NullInt32     `json:"staff_id"`
	CheckInDate       time.Time         `json:"check_in_date"`
	CheckOutDate      time.Time         `json:"check_out_date"`
	NumberOfGuests    int32             `json:"number_of_guests"`
	Status            ReservationStatus `json:"status"`
	BookingDate       time.Time         `json:"booking_date"`
	RoomNumber        string            `json:"room_number"`
	RoomType          RoomRoomType      `json:"room_type"`
	PricePerNight     string            `json:"price_per_night"`
	Nights            int32             `json:"nights"`
	TotalPrice        float64           `json:"total_price"`
	CustomerFirstName string            `json:"customer_first_name"`
	CustomerLastName  string            `json:"customer_last_name"`
	CustomerEmail     string            `json:"customer_email"`
	PaymentStatus     PaymentStatus     `json:"payment_status"`
}

type Room struct {
	RoomID        int32        `json:"room_id"`
	RoomNumber    string       `json:"room_number"`
	RoomType      RoomRoomType `json:"room_type"`
	PricePerNight string       `json:"price_per_night"`
	MaxOccupancy  int32        `json:"max_occupancy"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type Staff struct {
	StaffID      int32          `json:"staff_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Role         StaffRole      `json:"role"`
	Email        string         `json:"email"`
	Phone        sql.NullString `json:"phone"`
	PasswordHash string         `json:"password_hash"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
