// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentMethod string

const (
	PaymentMethodCash       PaymentMethod = "cash"
	PaymentMethodCreditCard PaymentMethod = "credit_card"
	PaymentMethodOnline     PaymentMethod = "online"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusCompleted PaymentStatus = "completed"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusRefunded  PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ReservationStatus string

const (
	ReservationStatusPending    ReservationStatus = "pending"
	ReservationStatusConfirmed  ReservationStatus = "confirmed"
	ReservationStatusCheckedIn  ReservationStatus = "checked_in"
	ReservationStatusCheckedOut ReservationStatus = "checked_out"
	ReservationStatusCancelled  ReservationStatus = "cancelled"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus
	Valid             bool // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type RoomRoomType string

const (
	RoomRoomTypeStandard  RoomRoomType = "Standard"
	RoomRoomTypeDeluxe    RoomRoomType = "Deluxe"
	RoomRoomTypeSuite     RoomRoomType = "Suite"
	RoomRoomTypePenthouse RoomRoomType = "Penthouse"
)

func (e *RoomRoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomRoomType(s)
	case string:
		*e = RoomRoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomRoomType: %T", src)
	}
	return nil
}

type NullRoomRoomType struct {
	RoomRoomType RoomRoomType
	Valid        bool // Valid is true if RoomRoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomRoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomRoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomRoomType), nil
}

type StaffRole string

const (
	StaffRoleReceptionist StaffRole = "receptionist"
	StaffRoleManager      StaffRole = "manager"
	StaffRoleAdmin        StaffRole = "admin"
)

func (e *StaffRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffRole(s)
	case string:
		*e = StaffRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffRole: %T", src)
	}
	return nil
}

type NullStaffRole struct {
	StaffRole StaffRole
	Valid     bool // Valid is true if StaffRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffRole) Scan(value interface{}) error {
	if value == nil {
		ns.StaffRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffRole), nil
}

type Customer struct {
	CustomerID    int32
	FirstName     string
	LastName      string
	Email         string
	Phone         string
	Address       sql.NullString
	LoyaltyPoints int32
	CreatedAt     sql.NullTime
}

type Payment struct {
	PaymentID      int32
	ReservationID  int32
	Amount         string
	PaymentDate    time.Time
	Method         PaymentMethod
	TransactionID  sql.NullString
	Status         PaymentStatus
	BillingName    string
	BillingEmail   string
	BillingAddress sql.NullString
}

type Reservation struct {
	ReservationID  int32
	CustomerID     int32
	RoomID         int32
	StaffID        sql.NullInt32
	CheckInDate    time.Time
	CheckOutDate   time.Time
	NumberOfGuests int32
	Status         ReservationStatus
	BookingDate    time.Time
}

type Reservationwithprice struct {
	ReservationID  int32
	CustomerID     int32
	RoomID         int32
	StaffID        sql.NullInt32
	CheckInDate    time.Time
	CheckOutDate   time.Time
	NumberOfGuests int32
	Status         ReservationStatus
	BookingDate    time.Time
	RoomNumber     string
	RoomType       RoomRoomType
	PricePerNight  string
	Nights         int32
	TotalPrice     float64
}

type Room struct {
	RoomID        int32
	RoomNumber    string
	RoomType      RoomRoomType
	PricePerNight string
	MaxOccupancy  int32
	CreatedAt     sql.NullTime
}

type Staff struct {
	StaffID      int32
	FirstName    string
	LastName     string
	Role         StaffRole
	Email        string
	Phone        sql.NullString
	PasswordHash string
	IsActive     bool
	CreatedAt    sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
