// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO Payment (reservation_id, amount, method, transaction_id, status, billing_name, billing_email, billing_address)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	ReservationID  int32          `json:"reservation_id"`
	Amount         string         `json:"amount"`
	Method         PaymentMethod  `json:"method"`
	TransactionID  sql.NullString `json:"transaction_id"`
	Status         PaymentStatus  `json:"status"`
	BillingName    string         `json:"billing_name"`
	BillingEmail   string         `json:"billing_email"`
	BillingAddress sql.NullString `json:"billing_address"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment,
		arg.ReservationID,
		arg.Amount,
		arg.Method,
		arg.TransactionID,
		arg.Status,
		arg.BillingName,
		arg.BillingEmail,
		arg.BillingAddress,
	)
}

const getPaymentByReservation = `-- name: GetPaymentByReservation :one
SELECT payment_id, reservation_id, amount, payment_date, method, transaction_id, status, billing_name, billing_email, billing_address FROM Payment WHERE reservation_id = ?
`

func (q *Queries) GetPaymentByReservation(ctx context.Context, reservationID int32) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReservation, reservationID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.ReservationID,
		&i.Amount,
		&i.PaymentDate,
		&i.Method,
		&i.TransactionID,
		&i.Status,
		&i.BillingName,
		&i.BillingEmail,
		&i.BillingAddress,
	)
	return i, err
}

const getTotalRevenue = `-- name: GetTotalRevenue :one
SELECT CAST(COALESCE(SUM(amount), 0) AS CHAR) AS total_revenue FROM Payment WHERE status = 'completed'
`

func (q *Queries) GetTotalRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalRevenue)
	var total_revenue interface{}
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT payment_id, reservation_id, amount, payment_date, method, transaction_id, status, billing_name, billing_email, billing_address FROM Payment ORDER BY payment_date DESC
`

func (q *Queries) ListAllPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.ReservationID,
			&i.Amount,
			&i.PaymentDate,
			&i.Method,
			&i.TransactionID,
			&i.Status,
			&i.BillingName,
			&i.BillingEmail,
			&i.BillingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundPayment = `-- name: RefundPayment :exec
UPDATE Payment SET status = 'refunded' WHERE reservation_id = ?
`

func (q *Queries) RefundPayment(ctx context.Context, reservationID int32) error {
	_, err := q.db.ExecContext(ctx, refundPayment, reservationID)
	return err
}
