// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelReservation = `-- name: CancelReservation :exec
UPDATE Reservation SET status = 'cancelled' WHERE reservation_id = ? AND customer_id = ?
`

type CancelReservationParams struct {
	ReservationID int32
	CustomerID    int32
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) error {
	_, err := q.db.ExecContext(ctx, cancelReservation, arg.ReservationID, arg.CustomerID)
	return err
}

const checkRoomAvailabilityForUpdate = `-- name: CheckRoomAvailabilityForUpdate :one
SELECT COUNT(*) AS count FROM Reservation
WHERE room_id = ?
AND status NOT IN ('cancelled', 'checked_out')
AND check_in_date < ? AND check_out_date > ?
FOR UPDATE
`

type CheckRoomAvailabilityForUpdateParams struct {
	RoomID       int32
	CheckInDate  time.Time
	CheckOutDate time.Time
}

func (q *Queries) CheckRoomAvailabilityForUpdate(ctx context.Context, arg CheckRoomAvailabilityForUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkRoomAvailabilityForUpdate, arg.RoomID, arg.CheckInDate, arg.CheckOutDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :execresult
INSERT INTO Reservation (customer_id, room_id, staff_id, check_in_date, check_out_date, number_of_guests, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReservationParams struct {
	CustomerID     int32
	RoomID         int32
	StaffID        sql.NullInt32
	CheckInDate    time.Time
	CheckOutDate   time.Time
	NumberOfGuests int32
	Status         ReservationStatus
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReservation,
		arg.CustomerID,
		arg.RoomID,
		arg.StaffID,
		arg.CheckInDate,
		arg.CheckOutDate,
		arg.NumberOfGuests,
		arg.Status,
	)
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT reservation_id, customer_id, room_id, staff_id, check_in_date, check_out_date, number_of_guests, status, booking_date FROM Reservation WHERE reservation_id = ?
`

func (q *Queries) GetReservationByID(ctx context.Context, reservationID int32) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservationByID, reservationID)
	var i Reservation
	err := row.Scan(
		&i.ReservationID,
		&i.CustomerID,
		&i.RoomID,
		&i.StaffID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.NumberOfGuests,
		&i.Status,
		&i.BookingDate,
	)
	return i, err
}

const listAllReservations = `-- name: ListAllReservations :many
SELECT reservation_id, customer_id, room_id, staff_id, check_in_date, check_out_date, number_of_guests, status, booking_date, room_number, room_type, price_per_night, nights, total_price FROM ReservationWithPrice ORDER BY booking_date DESC
`

func (q *Queries) ListAllReservations(ctx context.Context) ([]Reservationwithprice, error) {
	rows, err := q.db.QueryContext(ctx, listAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservationwithprice
	for rows.Next() {
		var i Reservationwithprice
		if err := rows.Scan(
			&i.ReservationID,
			&i.CustomerID,
			&i.RoomID,
			&i.StaffID,
			&i.CheckInDate,
			&i.CheckOutDate,
			&i.NumberOfGuests,
			&i.Status,
			&i.BookingDate,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.Nights,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByCustomer = `-- name: ListReservationsByCustomer :many
SELECT reservation_id, customer_id, room_id, staff_id, check_in_date, check_out_date, number_of_guests, status, booking_date, room_number, room_type, price_per_night, nights, total_price FROM ReservationWithPrice WHERE customer_id = ? ORDER BY booking_date DESC
`

func (q *Queries) ListReservationsByCustomer(ctx context.Context, customerID int32) ([]Reservationwithprice, error) {
	rows, err := q.db.QueryContext(ctx, listReservationsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservationwithprice
	for rows.Next() {
		var i Reservationwithprice
		if err := rows.Scan(
			&i.ReservationID,
			&i.CustomerID,
			&i.RoomID,
			&i.StaffID,
			&i.CheckInDate,
			&i.CheckOutDate,
			&i.NumberOfGuests,
			&i.Status,
			&i.BookingDate,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.Nights,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByStatus = `-- name: ListReservationsByStatus :many
SELECT reservation_id, customer_id, room_id, staff_id, check_in_date, check_out_date, number_of_guests, status, booking_date, room_number, room_type, price_per_night, nights, total_price FROM ReservationWithPrice WHERE status = ? ORDER BY booking_date DESC
`

func (q *Queries) ListReservationsByStatus(ctx context.Context, status ReservationStatus) ([]Reservationwithprice, error) {
	rows, err := q.db.QueryContext(ctx, listReservationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservationwithprice
	for rows.Next() {
		var i Reservationwithprice
		if err := rows.Scan(
			&i.ReservationID,
			&i.CustomerID,
			&i.RoomID,
			&i.StaffID,
			&i.CheckInDate,
			&i.CheckOutDate,
			&i.NumberOfGuests,
			&i.Status,
			&i.BookingDate,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.Nights,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE Reservation SET status = ? WHERE reservation_id = ?
`

type UpdateReservationStatusParams struct {
	Status        ReservationStatus
	ReservationID int32
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReservationStatus, arg.Status, arg.ReservationID)
	return err
}
