// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRoom = `-- name: CreateRoom :execresult
INSERT INTO Room (room_number, room_type, price_per_night, max_occupancy) VALUES (?, ?, ?, ?)
`

type CreateRoomParams struct {
	RoomNumber    string
	RoomType      RoomRoomType
	PricePerNight string
	MaxOccupancy  int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoom,
		arg.RoomNumber,
		arg.RoomType,
		arg.PricePerNight,
		arg.MaxOccupancy,
	)
}

const getAvailableRooms = `-- name: GetAvailableRooms :many
SELECT room_id, room_number, room_type, price_per_night, max_occupancy, created_at FROM Room
WHERE room_id NOT IN (
    SELECT room_id FROM Reservation
    WHERE status NOT IN ('cancelled', 'checked_out')
    AND check_in_date < ? AND check_out_date > ?
)
ORDER BY room_number
`

type GetAvailableRoomsParams struct {
	CheckInDate  time.Time
	CheckOutDate time.Time
}

func (q *Queries) GetAvailableRooms(ctx context.Context, arg GetAvailableRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableRooms, arg.CheckInDate, arg.CheckOutDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.MaxOccupancy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableRoomsByType = `-- name: GetAvailableRoomsByType :many
SELECT room_id, room_number, room_type, price_per_night, max_occupancy, created_at FROM Room
WHERE room_type = ?
AND room_id NOT IN (
    SELECT room_id FROM Reservation
    WHERE status NOT IN ('cancelled', 'checked_out')
    AND check_in_date < ? AND check_out_date > ?
)
ORDER BY room_number
`

type GetAvailableRoomsByTypeParams struct {
	RoomType     RoomRoomType
	CheckInDate  time.Time
	CheckOutDate time.Time
}

func (q *Queries) GetAvailableRoomsByType(ctx context.Context, arg GetAvailableRoomsByTypeParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableRoomsByType, arg.RoomType, arg.CheckInDate, arg.CheckOutDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.MaxOccupancy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT room_id, room_number, room_type, price_per_night, max_occupancy, created_at FROM Room WHERE room_id = ?
`

func (q *Queries) GetRoomByID(ctx context.Context, roomID int32) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.RoomNumber,
		&i.RoomType,
		&i.PricePerNight,
		&i.MaxOccupancy,
		&i.CreatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, room_number, room_type, price_per_night, max_occupancy, created_at FROM Room ORDER BY room_number
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomNumber,
			&i.RoomType,
			&i.PricePerNight,
			&i.MaxOccupancy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE Room SET room_number = ?, room_type = ?, price_per_night = ?, max_occupancy = ? WHERE room_id = ?
`

type UpdateRoomParams struct {
	RoomNumber    string
	RoomType      RoomRoomType
	PricePerNight string
	MaxOccupancy  int32
	RoomID        int32
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom,
		arg.RoomNumber,
		arg.RoomType,
		arg.PricePerNight,
		arg.MaxOccupancy,
		arg.RoomID,
	)
	return err
}
