// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"
)

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT staff_id, first_name, last_name, role, email, phone, password_hash, is_active, created_at FROM Staff WHERE email = ?
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByEmail, email)
	var i Staff
	err := row.Scan(
		&i.StaffID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
